export const ADD_TO_CART = 'ADD TO CART';
export const CHANGE_MESSAGES = 'CHANGE_MESSAGES';
export const REMOVE_ITEM_IN_CART = 'REMOVE_ITEM_IN_CART';
export const UPDATE_ITEM_IN_CART = 'UPDATE_ITEM_IN_CART';
export const FETCH_PRODUCT = 'FETCH_PRODUCTS ';
export const UPDATE_PRODUCT = 'UPDATE_PRODUCT';
export const DELETE_PRODUCT = 'DELETE_PRODUCT';
export const ADD_PRODUCT = 'ADD_PRODUCT';
